### ISSUE TITLE
EmuGUI.exe opens command prompt and does nothing

### ISSUE THREAD

**Issue by TheUniKian** [Tech-FZ/EmuGUI#59] opened 2023-06-09 04:33 UTC
No install, no file changes from what I can see, etc. I have installed all dependencies including "requests" and have followed all steps. Unfortunately the documentation calls for executing "main.exe" which doesnt exist in the current version as far as I can tell. I have no log I can provide, as one was not made by the program.

**Comment by Tech-FZ** [comment] 2023-06-09 10:18
EmuGUI doesn't log anything and yes, the executable has been renamed to "emugui.exe". Which version of EmuGUI are you running? Which operating system? Which hardware are you working on? That would help me a lot.

**Comment by TheUniKian** [comment] 2023-06-09 12:17
Version 1.1.0.5408, Windows 10 Pro 22H2

ASUS Z790 platform
intel i5 12600K
RX 6700XT
32GB DDR5 RAM
4TB GM7000 SSD
850w PSU

Unless my thunderbolt card or fan controller is messing with the compiler I don't think there is any other hardware.

**Comment by Tech-FZ** [comment] 2023-06-09 13:01
Have you tried running "emugui.exe"?

**Comment by TheUniKian** [comment] 2023-06-09 13:04
Yes, it opens a command prompt window and immediately closes it. Same happens if I try to run in administrator.

**Comment by Tech-FZ** [comment] 2023-06-09 13:09
Are you running an official version of Windows as recommended?

**Comment by TheUniKian** [comment] 2023-06-09 13:11
Running QEMU 8.0.2 as collected from qemu.org and attempting to install EmuGUI from the files of this github.

**Comment by Tech-FZ** [comment] 2023-06-09 13:11
I precompiled binaries you can download from https://github.com/Tech-FZ/EmuGUI/releases/tag/v1.1.0.5408

**Comment by Tech-FZ** [comment] 2023-06-09 13:15
Have you updated to Python 3.11? If yes, you may need to downgrade to Python 3.10.

**Comment by TheUniKian** [comment] 2023-06-09 13:36
Let me try to downgrade

**Comment by TheUniKian** [comment] 2023-06-09 13:59
Okay, well it stayed open long enough for me to be able to see `SQLite modual has encountered an error`, so I tried installing that but then it said I needed Visual C++ 14.0 or greater, so I installed that and restarted. I installed the 2022 latest versions of it. Now SQLite is telling me it cant make the `io.h` file in the  C:\Users\<user>\AppData\Local\Programs\Python\Python310\include\pyconfig.h directory and that C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe failed

I'm going to try and fix this and get back to you

**Comment by Tech-FZ** [comment] 2023-06-09 15:04
Try to run `pip install --reinstall pysqlite3`. Maybe the situation gets resolved.

**Comment by TheUniKian** [comment] 2023-06-09 16:34
Firstly, --reinstall is apparently an invalid option, second I am running into the issue in the image below
![Screenshot 2023-06-09 113243](https://github.com/Tech-FZ/EmuGUI/assets/59150963/81aca37e-d25b-41e4-8504-12ed61c37c38)

I don't believe this is an issue with your program, but the issue persists despite SQLite3 being in Python 3.10 by default. I cant truly find a cause or a resolution for this.

**Comment by TheUniKian** [comment] 2023-06-09 18:18
I jumped through a ton of hoops, but I got pysqlite3 installed, unfortunately it did not change the error when running EmuGUI

**Comment by Tech-FZ** [comment] 2023-06-09 19:11
Activate the Administrator account and run EmuGUI with that.

**Comment by TheUniKian** [comment] 2023-06-09 19:49
Still nothing, i'd try to see if the error has changed but OBS doesnt work when a file is ran as administrator

**Comment by Tech-FZ** [comment] 2023-06-09 21:03
Maybe check if there is something wrong with Windows.

**Comment by TheUniKian** [comment] 2023-06-10 01:17
How would I go about checking that?

**Comment by Tech-FZ** [comment] 2023-06-10 07:24
Run the command prompt as administrator and run `sfc /scannow`.

**Comment by Tech-FZ** [comment] 2023-06-10 11:15
Maybe this update fixes the issue: https://github.com/Tech-FZ/EmuGUI/releases/tag/v1.1.1.5409

**Comment by KoghaandSooga** [comment] 2023-08-30 14:02
I know this sounds lunatic but I'm serious when  I say this:  I haven't looked at this in a long time so decided to try the latest update which came out 20 hours ago and it does the same problem as this thread describes.  IE: Opens command prompt which says something briefly too fast to read then closes.  So no it's not on our end.

**Comment by KoghaandSooga** [comment] 2023-08-30 14:03
> I jumped through a ton of hoops, but I got pysqlite3 installed, unfortunately it did not change the error when running EmuGUI

I'm sorry you had to go thru that but glad you posted the results as I have the same issue too of it opening a command prompt. Glad I didn't try the things you did.  I use Python for BOTW MODS which if I updated it then it is known to break as people complain the latest Python is no good.

**Comment by Tech-FZ** [comment] 2023-08-30 15:35
I'm sorry it's still a problem. Try to open the command prompt in the EmuGUI folder and run the executable from there.

**Comment by KoghaandSooga** [comment] 2023-08-31 17:24
> I'm sorry it's still a problem. Try to open the command prompt in the EmuGUI folder and run the executable from there.

I'll give it a go but I'll have to redownload it.

**Comment by KoghaandSooga** [comment] 2023-09-30 15:04
> EmuGUI 1.2 will probably feel more mature, thanks to new debugging features I am working on.

I tried it again and it still the same where it waits about 1 min and then closes with something so fast you don't see it.

**Comment by jcalve** [comment] 2023-10-18 10:02
![Captura de pantalla 2023-10-18 120144](https://github.com/Tech-FZ/EmuGUI/assets/6191366/24ac7d45-ef91-4369-93a2-18bd2efb2e90)

**Comment by KoghaandSooga** [comment] 2023-10-20 08:20
> ![Captura de pantalla 2023-10-18 120144](https://user-images.githubusercontent.com/6191366/276204569-24ac7d45-ef91-4369-93a2-18bd2efb2e90.png)

How did you get the error to show and did you ever make the problem go away so it can run properly? I got it to run once a long time ago.

**Comment by jcalve** [comment] 2023-10-20 08:42
> 
> How did you get the error to show and did you ever make the problem go away so it can run properly? I got it to run once a long time ago before one of the major Windows updates so I do know this program was once capable of operating WITHOUT errors but it was still very glitch to use when I did use it. IE: Mouse kept always going off the edge whether I was in full screen or not.

You can see the error by running the .exe from a terminal as seen in the top of the screenshot, I was not able to make it run properly.

**Comment by KoghaandSooga** [comment] 2024-03-02 23:08
> I'll join the conversation here. I have the same problem with (probably) different cause.
> 
> ![grafik](https://private-user-images.githubusercontent.com/37399229/308586995-71dc65b5-dc80-4aa1-894c-ff85b2651600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MjEwMzAsIm5iZiI6MTcwOTQyMDczMCwicGF0aCI6Ii8zNzM5OTIyOS8zMDg1ODY5OTUtNzFkYzY1YjUtZGM4MC00YWExLTg5NGMtZmY4NWIyNjUxNjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDIzMDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNzBjMjc0NWU1ZWM5Njc0NzhkYjEwNzZkZTIzMDc0NDM5Y2ZjNDAwZDBkMGYxNWFiMzI1ZjZlMThjZWMzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.afL8VmMeUikumzcUB7upfFMmqypYObE7d1rnfWdOHmI)
> 
> Tested on [v1.2.0.5510](https://github.com/Tech-FZ/EmuGUI/releases/tag/v1.2.0.5510) to [v1.2.3.5513](https://github.com/Tech-FZ/EmuGUI/releases/tag/v1.2.3.5513)
> 
> What am I doing wrong? :D

I don't think you or I are actually doing anything wrong and quite possibly neither is the author of the emulator the issue is more complex as stated below.

First of all:  I have gotten this to (sort of) work only one time and it froze a lot and could never get the mouse to stay within the window: It never again worked since I have had Windows Updates prior. MS is known to brick machines they don't want to support when XP ended about the same time thousands of people who were using XP had their machines lock up after the final update forcing them (and us) to buy all new machines so I think coding in MS might be conflicting with some kind of address in the EXE which wherever it's pointing too doesn't actually exist anymore.  Hence the panic error.

**Comment by m0lDaViA** [comment] 2024-03-04 16:12
> > I'll join the conversation here. I have the same problem with (probably) different cause.
> > ![grafik](https://private-user-images.githubusercontent.com/37399229/308586995-71dc65b5-dc80-4aa1-894c-ff85b2651600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MjEwMzAsIm5iZiI6MTcwOTQyMDczMCwicGF0aCI6Ii8zNzM5OTIyOS8zMDg1ODY5OTUtNzFkYzY1YjUtZGM4MC00YWExLTg5NGMtZmY4NWIyNjUxNjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDIzMDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNzBjMjc0NWU1ZWM5Njc0NzhkYjEwNzZkZTIzMDc0NDM5Y2ZjNDAwZDBkMGYxNWFiMzI1ZjZlMThjZWMzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.afL8VmMeUikumzcUB7upfFMmqypYObE7d1rnfWdOHmI)
> > Tested on [v1.2.0.5510](https://github.com/Tech-FZ/EmuGUI/releases/tag/v1.2.0.5510) to [v1.2.3.5513](https://github.com/Tech-FZ/EmuGUI/releases/tag/v1.2.3.5513)
> > What am I doing wrong? :D
> 
> I don't think you or I are actually doing anything wrong and quite possibly neither is the author of the emulator the issue is more complex as stated below.
> 
> First of all: I have gotten this to (sort of) work only one time and it froze a lot and could never get the mouse to stay within the window: It never again worked since I have had Windows Updates prior. MS is known to brick machines they don't want to support when XP ended about the same time thousands of people who were using XP had their machines lock up after the final update forcing them (and us) to buy all new machines so I think coding in MS might be conflicting with some kind of address in the EXE which wherever it's pointing too doesn't actually exist anymore. Hence the panic error.
> 
> To summarize an update of Microsoft changed something and the program is doing what it is designed to do when a hard lock happens and it has a panic error as a result and I don't think there is anything the author can do other then abandon the program as it is clear Windows users can't use it.

You see the path in my picture right? The user, specified in the path, doesn't even exist. There is no such user nor such "old" profile hence i don't even understand how the program comes to that conclusion.
Even "old, not anymore existing" paths can't point to something which doesn't exist nor ever existed.
Therefore must be something other being wrong in the code.

**Comment by Tech-FZ** [comment] 2024-03-10 10:28
I'll try to investigate the issue and give you the results as soon as they are in.

**Comment by Tech-FZ** [comment] 2024-03-10 10:31
Meanwhile, you can get the source code, install Python and the EmuGUI dependencies and run the emugui.py file.

**Comment by Tech-FZ** [comment] 2024-03-10 13:22
While testing on Windows 11 23H2 x64, I ran into this issue at first:
![vmplayer_w9NDkNryCv](https://github.com/Tech-FZ/EmuGUI/assets/86562548/2bc202f6-9dda-441d-9406-920156f0b290)

After installing Microsoft Visual C++ 2022 tho, I did get it running as it should. Maybe try reinstalling said component?

**Comment by m0lDaViA** [comment] 2024-03-11 19:57
Well, i don't think that's the issue because we would have got the same error message then but i had to install a fresh copy of windows anyways and now it's working xD

**Comment by Tech-FZ** [comment] 2024-03-14 16:15
I guess we can close this issue then.

**Closed by Tech-FZ** 2024-03-14 16:15 UTC

**Comment by KoghaandSooga** [comment] 2024-03-19 16:20
By going to an older QEMU 7.0 and QTEMU I got it to once install XP but then it won't turn on ever again. By not turning on I mean the actual emulator giving error messages saying it can't find a bunch of machines I haven't had in a long time even if I do a fresh install it will just keep saying that. I think the only thing to do if I want to use this is a fresh install of Windows which just isn't worth the BS Microsoft puts you thru with accounts and all that.
